### ISSUE TITLE
proxy_configuration

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/edgecontroller#32] opened 2020-05-28 08:15 UTC
@amr-mokhtar proxy_os_enable is set to false. deploy_ne.sh script for controller and edge node is successful. But when I'm trying to execute kubectl command. I'm facing error like this. My network doesnot use proxy server.
<img width="960" alt="kubectl_version_error" src="https://user-images.githubusercontent.com/64581852/83116465-70e37380-a0e9-11ea-8a41-e8952c7ad77d.png">

**Comment by amr-mokhtar** [comment] 2020-06-05 19:25
Duplicate of https://github.com/open-ness/edgecontroller/issues/30

**Closed by amr-mokhtar** 2020-06-05 19:25 UTC
